version: '2'
services:
  ms-eureka-single:
    image: study/ms-eureka:latest
    environment:
      TZ: Asia/Shanghai
      port: 7000
      eureka_hostname: myeureka00.com
      spring.profiles.active: docker
      eureka_service_url: http://myeureka00.com:7000/eureka/
      COLLECTOR_IP: 192.168.110.170
    ports:
      - "7000:7000"
    volumes:
      - /etc/hosts:/etc/hosts
      - /data/logs:/data/logs
      - /etc/localtime:/etc/localtime

  ms-provider-single:
    image: study/ms-provider:latest
    environment:
      TZ: Asia/Shanghai
      port: 9000
      spring.profiles.active: docker
      jdbc_url: jdbc:mysql://192.168.110.170:3306/cloudDB01
      jdbc_usernamel: root
      jdbc_password: 123456
      eureka_service_url: http://myeureka00.com:7000/eureka/
      COLLECTOR_IP: 192.168.110.170
    ports:
      - "9000:9000"
    volumes:
      - /etc/hosts:/etc/hosts
      - /data/logs:/data/logs
      - /etc/localtime:/etc/localtime


  ms-consumer-single:
    image: study/ms-consumer:latest
    environment:
      TZ: Asia/Shanghai
      port: 8000
      spring.profiles.active: docker
      eureka_service_url: http://myeureka00.com:7000/eureka/
      COLLECTOR_IP: 192.168.110.170
    ports:
      - "8000:8000"
    volumes:
      - /etc/hosts:/etc/hosts
      - /data/logs:/data/logs
      - /etc/localtime:/etc/localtime



  ms-gateway-single:
    image: study/ms-gateway:latest
    environment:
      TZ: Asia/Shanghai
      port: 9527
      spring.profiles.active: docker
      eureka_service_url: http://myeureka00.com:7000/eureka/
      COLLECTOR_IP: 192.168.110.170
    ports:
      - "9527:9527"
    volumes:
      - /etc/hosts:/etc/hosts
      - /data/logs:/data/logs
      - /etc/localtime:/etc/localtime

