server:
  port: 9000

spring:
  profiles:
    active: dev
  application:
    name: microservicecloud-provider
  datasource:
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200      # 等待连接获取的最大超时时间
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

microservicecloud.url:
  provider: http://MICROSERVICECLOUD-PROVIDER
  consumer: http://MICROSERVICECLOUD-CONSUME
  gateway: http://MICROSERVICECLOUD-ZUUL-GATEWAY
