
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.110.170:3306/cloudDB01              # 数据库名称
    username: root
    password: 123456

eureka:
 instance:
   instance-id: ${spring.application.name}:${server.port}
   prefer-ip-address: true     #访问路径可以显示IP地址
 client: #客户端注册进eureka服务列表内
   service-url:
     defaultZone: http://myeureka00.com:7000/eureka/


