server:
  port: 8000

spring:
  profiles:
    active: dev
  application:
    name: microservicecloud-consumer

feign:
  hystrix:
    enabled: true

info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

microservicecloud.url:
  provider: http://MICROSERVICECLOUD-PROVIDER
  consumer: http://MICROSERVICECLOUD-CONSUME
  gateway: http://MICROSERVICECLOUD-ZUUL-GATEWAY
