server:
  port: 9527

spring:
  profiles:
    active: dev
  application:
    name: microservicecloud-zuul-gateway

zuul:
#  prefix: /atguigu
 ignored-services: "*"
 routes:
   consumer:
     serviceId: microservicecloud-consumer
     path: /consumer/**
     sensitiveHeaders: "*"
   provider:
     serviceId: microservicecloud-provider
     path: /provider/**
     sensitiveHeaders: "*"
   gateway:
     serviceId: microservicecloud-zuul-gateway
     path: /gateway/**
     sensitiveHeaders: "*"


microservicecloud.url:
  provider: http://MICROSERVICECLOUD-PROVIDER
  consumer: http://MICROSERVICECLOUD-CONSUME
  gateway: http://MICROSERVICECLOUD-ZUUL-GATEWAY
info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
