server:
  port: 7000

spring:
  profiles:
    active: dev
  application:
    name: microservicecloud-eureka

info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$