
eureka:
 instance:
   instance-id: ${spring.application.name}:${server.port}
   prefer-ip-address: true     #访问路径可以显示IP地址
 client: #客户端注册进eureka服务列表内
   service-url:
     defaultZone: http://myeureka00.com:7000/eureka/